# Generated by Django 5.1.1 on 2025-05-24 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='FormattingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_template', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cloned_from_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.formattingprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'formatting_profiles',
            },
        ),
        migrations.CreateModel(
            name='ContentsFormatting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_size', models.IntegerField()),
                ('font_name', models.CharField(max_length=100)),
                ('formatting_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.formattingprofile')),
            ],
            options={
                'db_table': 'contents_formatting',
            },
        ),
        migrations.CreateModel(
            name='BlankParagraphFormatting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('start_index', models.IntegerField()),
                ('para', models.TextField()),
                ('formatting_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.formattingprofile')),
            ],
            options={
                'db_table': 'blank_paragraph_formatting',
            },
        ),
        migrations.CreateModel(
            name='BlankPagesFormatting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=255)),
                ('paras', models.TextField()),
                ('formatting_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.formattingprofile')),
            ],
            options={
                'db_table': 'blank_pages_formatting',
            },
        ),
        migrations.CreateModel(
            name='FormulaFormatting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ole_count', models.IntegerField()),
                ('math_count', models.IntegerField()),
                ('default_page_width', models.FloatField()),
                ('formatting_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.formattingprofile')),
            ],
            options={
                'db_table': 'formula_formatting',
            },
        ),
        migrations.CreateModel(
            name='GeneralFormatting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_spacing', models.FloatField()),
                ('font_name', models.CharField(max_length=100)),
                ('font_size', models.IntegerField()),
                ('formatting_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.formattingprofile')),
            ],
            options={
                'db_table': 'general_formatting',
            },
        ),
        migrations.CreateModel(
            name='ImageDiagramFormatting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=512)),
                ('images', models.TextField()),
                ('num_chart', models.IntegerField()),
                ('formatting_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.formattingprofile')),
            ],
            options={
                'db_table': 'image_diagram_formatting',
            },
        ),
        migrations.CreateModel(
            name='ListFormatting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_indent_cm', models.FloatField()),
                ('additional_indent_cm', models.FloatField()),
                ('hanging_indent', models.FloatField()),
                ('formatting_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.formattingprofile')),
            ],
            options={
                'db_table': 'list_formatting',
            },
        ),
        migrations.CreateModel(
            name='NumberingHeadingsFormatting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_name', models.CharField(max_length=100)),
                ('font_size_headlines', models.IntegerField()),
                ('font_color_rgb', models.CharField(max_length=20)),
                ('formatting_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.formattingprofile')),
            ],
            options={
                'db_table': 'numbering_headings_formatting',
            },
        ),
        migrations.CreateModel(
            name='PageNumberingFormatting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=512)),
                ('run', models.CharField(max_length=255)),
                ('name_doc_os', models.CharField(max_length=255)),
                ('formatting_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.formattingprofile')),
            ],
            options={
                'db_table': 'page_numbering_formatting',
            },
        ),
        migrations.CreateModel(
            name='TableFormatting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para_alignment_headlines', models.CharField(max_length=100)),
                ('interval_after_paragraph', models.FloatField()),
                ('interval_before_paragraph', models.FloatField()),
                ('formatting_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.formattingprofile')),
            ],
            options={
                'db_table': 'table_formatting',
            },
        ),
        migrations.CreateModel(
            name='UpdatingContentsFormatting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_name', models.CharField(max_length=100)),
                ('font_bold', models.BooleanField(default=False)),
                ('font_size', models.IntegerField()),
                ('formatting_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.formattingprofile')),
            ],
            options={
                'db_table': 'updating_contents_formatting',
            },
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=512)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=50)),
                ('formatting_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.formattingprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'uploaded_documents',
            },
        ),
        migrations.CreateModel(
            name='FormattingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pages', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('download_link', models.CharField(max_length=512)),
                ('formatted_at', models.DateTimeField(auto_now_add=True)),
                ('formatting_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.formattingprofile')),
                ('uploaded_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.uploadeddocument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'formatting_history',
            },
        ),
        migrations.CreateModel(
            name='UserProfileChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('chosen_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chosen_by_users', to='users.formattingprofile')),
                ('custom_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_by_users', to='users.formattingprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'user_profile_choices',
            },
        ),
        migrations.CreateModel(
            name='UserQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'user_questions',
            },
        ),
    ]
